Install the (JACK-compatible) binaries if build
ninodewit/SHIRO-Plugins pull request #3
Opened 2017-05-16 14:13 UTC by trebmuh

2018-03-21 13:40 UTC, trebmuh commented
@ninodewit : any issue with merging this one?

2019-11-17 15:47 UTC, trebmuh commented
ping

2020-11-09 20:36 UTC, trebmuh commented
yearly ping @ninodewit

2020-11-09 21:01 UTC, ninodewit commented on Makefile
> +	cp -r bin/Pitchotto  $(DESTDIR)$(PREFIX)/bin/
- [ ] please remove this line, Pitchotto was never completed and abandoned at some point.

2020-11-09 21:05 UTC, ninodewit requested changes
I'm sorry it took me years to respond. Not sure if I'll be pushing any new stuff here but if this PR helps you and other JACK users it's good to go other than the one line.

2020-11-09 21:07 UTC, ninodewit approved these changes

2020-11-09 21:07 UTC, merged

2020-11-09 21:10 UTC, trebmuh commented
Thank you for the merge.